<?xml version="1.0" encoding="utf-8"?>
<!--  -*- Mode: xmldoc -*-  -->
<!DOCTYPE book [
<!ELEMENT book (chapter*)>
<!ELEMENT chapter (title,type,arguments?,package?,description,seealso*,link*,section,file?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT arguments (#PCDATA)>
<!ELEMENT package (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT seealso (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT file (#PCDATA)>
]>
<!--
book
  └ chapter
      ├ title
      ├ type           Function, Special Form, Macro
      │                Misc, Tips, Variable, BufferLocal
      │                Keyword, Accessor
      ├ arguments      VariableやTipsはなし
      ├ package        Tipsはなし
      ├ description
      ├ seealso        0?n個
      ├ link           0?n個
      ├ section        データ型 変数と定数 制御構造
      │                パッケージ 関数 マクロ シンボル
      │                数値 文字 文字列 シーケンス
      │                リスト ハッシュ 配列 チャンク
      │                評価 入出力 ファイルシステム
      │                エラー ウィンドウ バッファ
      │                ミニバッファ リージョン モード
      │                シンタックス キーマップ テキスト
      │                検索・正規表現 ダイアログ 日付・時間
      │                メニュー ファイラ ポジション
      │                プロセス システム その他
      └ file            0 or 1
-->
<!--
<!ELEMENT (a, b)>     順番に出現
<!ELEMENT (a|b|c)>    どれか１つが出現
<!ELEMENT x (a?)>     0または1出現
<!ELEMENT x (a+)>     1回以上出現
<!ELEMENT x (a*)>     0回以上出現
-->
<!--
Copyright (c) 2007 The Xyzzy Documentation Project
Copyright (C) 2012 xyzzy Project

Permission is hereby granted, free of charge, to any person obtaining a 
copy of this software and associated documentation files (the "Software"), 
to deal in the Software without restriction, including without 
limitation the rights to use, copy, modify, merge, publish, distribute, 
sublicense, and/or sell copies of the Software, and to permit persons to 
whom the Software is furnished to do so, subject to the following 
conditions:

The above copyright notice and this permission notice shall be included 
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<!--
制作著作：xyzzy reference.xml(気が向いたら)作成プロジェクト・メンバー
        逸見雅人        henmi@synform.co.jp
        服部昌司        gyo@he.mirai.ne.jp
        サイトウ        HiroshiSaito@pob.org
        山本泰三        ymtz@pop02.odn.ne.jp
        花井達          変換ツール作成協力
        s.oowada
        OHKUBO KOHEI    kuboon@mbe.nifty.com
        HIE Masahiro    madoinu@ybb.ne.jp
        SANO Masatoshi  t01450ms@sfc.keio.ac.jp
        Nobuaki Arima   narima1109@hotmail.com
        広井誠          m_hiroi@yahoo.co.jp
        ※敬称略
-->
<!--
reference.xmlについての詳細は以下のサイトにて
・http://xyzzy.s53.xrea.com/wiki/?%A5%EA%A5%D5%A5%A1%A5%EC%A5%F3%A5%B9
-->
<book>


<chapter>
<title>*</title>
<type>Function</type>
<arguments>* &amp;rest NUMBERS</arguments>
<package>lisp</package>
<description>
引数を全て乗算した数値を返します。

使用例：  
  (* 1 2 3)
  =&gt; 6
</description>
<seealso>/</seealso>
<section>数値</section>
<file>builtin.l</file>
</chapter>

<chapter>
<title>Emacs 互換ではない正規表現は結構あるのでしょうか？</title>
<type>Tips</type>
<arguments></arguments>
<package></package>
<description>
\'  \`  \=  \c  \C これだけです。
</description>
<section>検索・正規表現</section>
<file></file>
</chapter>

<chapter>
<title>*activate-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
バッファがactivateされたときに任意の処理を行うために使用されます。
デフォルトではファイルの修正日付を確認しています。
</description>
<seealso>verify-buffers-file-modtime</seealso>
<seealso>*deactivate-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*after-save-buffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
多分 save-buffer の最後に実行されます。
</description>
<seealso>save-buffer</seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*apropos-no-regexp*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
non-nil に設定すると、apropos 実行時に、正規表現のメタ文字はエスケープさ
れます。デフォルトは nil です。
</description>
<seealso>apropos</seealso>
<link></link>
<section>シンボル</section>
<file>help.l</file>
</chapter>

<chapter>
<title>*auto-fill-hook</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
auto-fill-mode の時に、self-insert-command から *last-command-char*
を引数として実行されます。普通は do-auto-fill が設定されています。
多分修正しない方が良いと思います。
※ run-hooks ではなく、 funcall されるので注意すること
</description>
<seealso>auto-fill-mode</seealso>
<seealso>auto-fill-hook</seealso>
<seealso>self-insert-command</seealso>
<seealso>funcall</seealso>
<link></link>
<section>変数と定数</section>
<file>cmds.l</file>
</chapter>

<chapter>
<title>*auto-mode-alist*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
モード判定用の連想リストです。(key . datum)の組で登録します。
(string-matchp key filename)がnon-nilになった場合に、
datumをfuncallします。

datumにdecode-auto-modeのプロパティが存在する場合には、バッファを
第一引数にしてdatumをfuncallします。
cc-mode.lのdecode-c-modeを参照

使用例：
  (pushnew '("\\.asp" . basic-mode) *auto-mode-alist* :test 'equal)
</description>
<seealso>*find-file-auto-mode-function*</seealso>
<seealso>*auto-mode-parameter-alist*</seealso>
<link></link>
<section>モード</section>
<file>defs.l</file>
</chapter>

<chapter>
<title>*auto-update-per-device-directory*</title>
<type>Variable</type>
<arguments></arguments>
<package>lisp</package>
<description>
ファイラで移動したときにドライブ毎のデフォルトのディレクトリについて制御します。

  t   移動するたびに更新する
  nil set-perdevice-directoryで指定したディレクトリに固定する
</description>
<seealso>set-per-device-directory</seealso>
<link></link>
<section>ファイルシステム</section>
<file></file>
</chapter>

<chapter>
<title>*before-delete-buffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
delete-bufferを継続するかどうかを制御します。登録された関数が一
つでもnilを返すとdelete-bufferを中止します。

参考：
  ;;; 呼び出し方
  (run-hook-with-args-until-success
       '*before-delete-buffer-hook* (selected-buffer))

使用例：
  (add-hook '*before-delete-buffer-hook* 'func)
  =&gt;(func)
  (defun func (x) (yes-or-no-p "delete-buffer ~A ?" (buffer-name x)))
  =&gt;func
</description>
<seealso>delete-buffer</seealso>
<seealso>*delete-buffer-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*before-find-file-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
find-fileの最初で実行されます。
※run-hook-with-args-until-successで実行されるので注意すること
</description>
<seealso>find-file</seealso>
<link></link>
<section>変数と定数</section>
<file>files.l</file>
</chapter>

<chapter>
<title>*before-save-buffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
多分 save-buffer の最初に実行されます。
※ run-hook-with-args-until-success で実行されるので注意すること
</description>
<seealso>save-buffer</seealso>
<seealso>run-hook-with-args-until-success</seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*buffer-bar-context-menu*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
バッファ・バー上で右クリックしたときに出てくるコンテキストメニューです。
define-popup-menu で作成されています。（作成は app-menu.l）
</description>
<section>バッファ</section>
<file>buffer.l</file>
</chapter>

<chapter>
<title>*buffer-bar-context-menu-buffer*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
バッファバー上で選択されているバッファです。ただし、バッファバー上の
コンテキストメニューで取得専用くらいしか使用できません。
</description>
<section>バッファ</section>
<file>buffer.l</file>
</chapter>

<chapter>
<title>*buffer-bar-context-menu-handler*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
デフォルトのバッファバー用コンテキストメニューハンドラです。
setq-default によって定義されている標準の動作は、 
*buffer-bar-context-menu-buffer* を定義し、*buffer-bar-context-menu* を
返します。
</description>
<seealso>*buffer-bar-context-menu*</seealso>
<section>バッファ</section>
<file>buffer.l</file>
</chapter>

<chapter>
<title>*buffer-bar-selected-buffer-to-first*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
non-nil なら、選択されたバッファがバッファバー上で一番先頭になります。
キーでタブを移動した場合は移動されません。デフォルトは nil です。
(setq *buffer-bar-selected-buffer-to-first* t) とやって、バッファバーを
クリックすれば分かると思います。
</description>
<section>バッファ</section>
<file></file>
</chapter>

<chapter>
<title>*buffer-menu-mode-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
buffer-menuの起動時に実行されます。

参考：
  (run-hooks '*buffer-menu-mode-hook*)
</description>
<seealso></seealso>
<link></link>
<section>メニュー</section>
<file>buf-menu.l</file>
</chapter>

<chapter>
<title>*change-buffer-colors-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
途中
</description>
<seealso></seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*command-line-mailto-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
コマンドラインで指定された -mailto オプションの引数を元に実行されます。 
※run-hooksではなくfuncallされるので注意すること
</description>
<seealso>起動時処理フロー</seealso>
<link></link>
<section>変数と定数</section>
<file>estartup.l</file>
</chapter>

<chapter>
<title>*command-output-mode-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
execute-subprocessの中でcommand-output-mode起動時に実行されます。
</description>
<seealso></seealso>
<link></link>
<section>モード</section>
<file>process.l</file>
</chapter>

<chapter>
<title>*create-buffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
多分create-new-bufferで実行されます。
</description>
<seealso>*default-buffer-mode*</seealso>
<seealso>create-new-buffer</seealso>
<seealso></seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*css-mode-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
css-mode起動時に実行されます。
</description>
<seealso></seealso>
<link></link>
<section>モード</section>
<file>css-mode.l</file>
</chapter>

<chapter>
<title>*css-level*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
css-modeで利用するCSS Levelを指定します。
デフォルトは 3 (CSS Level 3)です。

補足：
  xyzzy 0.2.2.236 から利用可能です。
</description>
<seealso></seealso>
<link></link>
<section>モード</section>
<file>css-mode.l</file>
</chapter>

<chapter>
<title>*css-keyword-file*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
css-modeで利用するCSS Level 2のキーワードファイルを指定します。
*css-level*が2の場合に読み込まれます。
</description>
<seealso></seealso>
<link></link>
<section>モード</section>
<file>css-mode.l</file>
</chapter>

<chapter>
<title>*css3-keyword-files*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
css-modeで利用するCSS Level 3のキーワードファイルを指定します。
*css-level*が3の場合に読み込まれます。

CSS3用のキーワードファイルはCSSモジュールごとに分かれているので、
必要なモジュールのキーワードのみを読み込むことができます。

デフォルトはCSS Level 3の全モジュール、ブラウザごとの拡張、
HTML4/5 の要素をキーワードとして読み込みます。

  ;; css-modeで利用するキーワードの設定 (CSS Level 3)
  (setq *css3-keyword-files*
    '(;; CSS3 modules
      "CSS3/2d-transforms"
      "CSS3/3d-transforms"
      "CSS3/animations"
      "CSS3/backgrounds-and-borders"
      "CSS3/basic-box"
      "CSS3/basic-user-interface"
      "CSS3/behavioral-extensions"
      "CSS3/color"
      "CSS3/flexible-box-layout"
      "CSS3/fonts"
      "CSS3/generated-and-replaced-content"
      "CSS3/hyperlinks"
      "CSS3/layout"
      "CSS3/line"
      "CSS3/lists"
      "CSS3/marquee"
      "CSS3/multi-column"
      "CSS3/paged-media"
      "CSS3/presentation-levels"
      "CSS3/ruby"
      "CSS3/speech"
      "CSS3/tables"
      "CSS3/text"
      "CSS3/transitions"
      ;; vendor extensions
      "CSS3/microsoft-extensions"
      "CSS3/mozilla-extensions"
      "CSS3/webkit-extensions"
      ;; HTML elements
      "CSS3/html4-elements"
      "CSS3/html5-elements"
      ))

補足：
  xyzzy 0.2.2.236 から利用可能です。
</description>
<seealso></seealso>
<link></link>
<section>モード</section>
<file>css-mode.l</file>
</chapter>

<chapter>
<title>*dabbrev-search-this-buffer-only*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
dabbrev-expandの検索対象を設定します。

  t   カレントバッファのみを検索します
  nil 全バッファを検索します
</description>
<seealso>dabbrev-expand</seealso>
<link></link>
<section>テキスト</section>
<file>dabbrev.l</file>
</chapter>

<chapter>
<title>*dabbrevs-no-undo*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
dabbrev-expand時のundoの方法を設定します。
dabbrev-expandを行なった際に候補が順次挿入されますが...
  non-nil  dabbrev-expandの直前まで一気に取り消す
  nil      途中の挿入過程を順番に取り消す
</description>
<seealso>undo</seealso>
<seealso>dabbrev-expand</seealso>
<link></link>
<section>バッファ</section>
<file>defs.l</file>
</chapter>

<chapter>
<title>*deactivate-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
バッファがdeactivateされたときに任意の処理を行うために使用されま
す。デフォルトではクリップボードの同期を行っています。
</description>
<seealso>*activate-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*default-buffer-mode*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
新しくバッファを作成した場合のモードを指定します。
例えば、lisp-modeを指定しておけば、新しく作成したバッファは全てlisp-mode
になります。

使用例：  
  (setq *default-buffer-mode* 'lisp-mode)
  =&gt; lisp-mode
  (switch-to-buffer "*new*")
  =&gt; #&lt;buffer: *new*&gt;
  buffer-mode
  =&gt; lisp-mode
</description>
<section>バッファ</section>
<file>defs.l</file>
</chapter>

<chapter>
<title>*default-load-path*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
siteinit.lから*load-path*を修正するために用いられます。
siteinit.lの直後に*default-load-path*の内容が、*load-path*にマー
ジされ、*pre-startup-hook*から有効になります。
追加するパスはリストで設定します。

使用例：
  (setq *default-load-path* '("C:/APPLICATIONS/XYZZY/lib"))
</description>
<seealso>*load-path*</seealso>
<link></link>
<section>変数と定数</section>
<file>misc.l</file>
</chapter>

<chapter>
<title>*delete-buffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
delete-bufferで実行されます。
</description>
<seealso>delete-buffer</seealso>
<seealso>*before-delete-buffer-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file></file>
</chapter>

<chapter>
<title>*diff-mode-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
diff起動時に実行されます。
</description>
<seealso></seealso>
<link></link>
<section>モード</section>
<file>diff.l</file>
</chapter>

<chapter>
<title>*do-completion</title>
<type>Function</type>
<arguments>*do-completion STRING TYPE &amp;optional WORDP LIST</arguments>
<package>editor</package>
<description>
指定した文字列を条件に従い補完します。

  STRING : 補完したい文字列
  TYPE   : 補完する型
        :symbol-name
        :function-name
        :command-name
        :variable-name
        :non-trivial-symbol-name
        :exist-file-name
        :file-name
        :file-name-list
        :directory-name
        :buffer-name
        :exist-buffer-name
        :list
        :list-ignore-case
  WORD   : nilでなければ単語ごとの補完
  LIST   : TYPE が :list か :list-ignore-case の場合の補完リスト

戻り値は以下のとおりです。

  多値で3つの値が戻ってきますので、multiple-value-bind で受け取るといい
  でしょう。complete.lの中にある do-completion-internal を参考にしてくだ
  さい。以下は場合分けをしています。

        [1] 補完の候補が存在しない場合     :no-completions と nil
        [2] マッチする候補がなかった場合   :no-match と nil
        [3] 与えられた文字列がすでに候補の
            いずれかと一致していて
            補完する必要がない場合
            [3.1] 一致した候補が一つだけ   :solo-match と list と prefix
            [3.2] 複数と一致した場合       :not-unique と list と prefix
        [4] 補完した場合                   補完した結果の文字列と list と prefix

  list は、一致した候補のリスト。
  prefix は、例えばファイル名の補完のときのディレクトリ名とか、
  シンボルの補完のときのパッケージ修飾部分とか。
</description>
<section>テキスト</section>
<file>builtin.l</file>
</chapter>

<chapter>
<title>*drag-and-drop-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
D&amp;D時に実行されます。デフォルトでは、D&amp;D先がミニバッファ
ならミニバッファへの入力として扱い、それ以外ならfind-fileする
ようになっています。

※run-hooksではなくfuncallされます。引数は2つで、ドロップされたウィンド
  ウとドロップしたファイルのリストです。
</description>
<seealso></seealso>
<link></link>
<section>変数と定数</section>
<file>mouse.l</file>
</chapter>

<chapter>
<title>*enter-minibuffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ミニバッファに入ったときに実行されます。(interactive...)で指定さ
れた引数が渡されます。
</description>
<seealso></seealso>
<link></link>
<section>ミニバッファ</section>
<file></file>
</chapter>

<chapter>
<title>*eol-cr*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
改行コードのCRを表す値です。
プロセスやバッファの入出力の改行コードを設定するのに使用します。
</description>
<seealso>*eol-lf*</seealso>
<seealso>*eol-crlf*</seealso>
<seealso>set-buffer-eol-code</seealso>
<link></link>
<section>入出力</section>
<file>encoding.l</file>
</chapter>

<chapter>
<title>*eol-crlf*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
改行コードのCRLFを表す値です。
プロセスやバッファの入出力の改行コードを設定するのに使用します。
</description>
<seealso>*eol-cr*</seealso>
<seealso>*eol-lf*</seealso>
<seealso>set-buffer-eol-code</seealso>
<link></link>
<section>入出力</section>
<file>encoding.l</file>
</chapter>

<chapter>
<title>*eol-lf*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
改行コードのLFを表す値です。
プロセスやバッファの入出力の改行コードを設定するのに使用します。
</description>
<seealso>*eol-cr*</seealso>
<seealso>*eol-crlf*</seealso>
<seealso>set-buffer-eol-code</seealso>
<link></link>
<section>入出力</section>
<file>encoding.l</file>
</chapter>

<chapter>
<title>*error-regexp-list*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
first-error/next-errorで使用するエラー発生位置の表記形式を変更することが可能です。
*error-regexp-list*の形式は以下のとおりです。

  ((正規表現1 ファイル名のマッチ位置1 行のマッチ位置1)
   (正規表現2 ファイル名のマッチ位置2 行のマッチ位置2)
    ...
   (正規表現N ファイル名のマッチ位置N 行のマッチ位置N))

[xyzzy:05447]で亀井さんが示しているとおり、pushを使って追加するのが無難です。
(push (list (compile-regexp "^\"\\([^\"\n]+\\)\", line \\([0-9]+\\):") 1 2)
      *error-regexp-list*)
</description>
<seealso>next-error</seealso>
<seealso>first-error</seealso>
<link></link>
<section>エラー</section>
<file>errors.l</file>
</chapter>

<chapter>
<title>*etc-path*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
キーワードファイル等を格納するパスが設定されています。
標準では(merge-pathnames "etc" (si:system-root))が設定されています。

参照例：
  *etc-path*
  =&gt; "C:/APPLICATIONS/XYZZY/etc"
</description>
<seealso>etc-path</seealso>
<link></link>
<section>変数と定数</section>
<file>misc.l</file>
</chapter>

<chapter>
<title>*executing-macro*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
マクロを実行中か否かを返します。
  t    マクロを実行中
  nil  マクロを実行中ではない
</description>
<seealso></seealso>
<link></link>
<section>マクロ</section>
<file>cmds.l</file>
</chapter>

<chapter>
<title>*exit-minibuffer-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ミニバッファから出たときに実行されます。
</description>
<seealso></seealso>
<link></link>
<section>ミニバッファ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-chdir-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
（ファイラでディレクトリが変更されたりすると実行されます。用途不明） 
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-chdir-primary-p*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
（詳細不明）
<!-- ファイラにてアクティブなウィンドウのディレクトリを変更したかどうか。 -->
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-click-toggle-marks-always*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
nilなら、ファイラで左クリックしたとき、その位置にカーソルがある場合の
みマークを反転します。
non-nil なら、カーソルの移動とマークの反転の両方を同時に行います。
デフォルトは t です。
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-directories*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラのジャンプ用のディレクトリを連想リストで設定します。

使用例：
  (setq *filer-directories*
      '((" [デスクトップ]" . "c:/windows/デスクトップ")
        (" [スプール]" . "c:/spool")))
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file>filer.l</file>
</chapter>

<chapter>
<title>*filer-drag-and-drop-helper</title>
<type>Function</type>
<arguments>*filer-drag-and-drop-helper EFFECT FILES SRC DEST</arguments>
<package>editor</package>
<description>
（詳細不明）
<!-- ファイラへドラッグアンドドロップした時の動作です。 -->
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file>filer.l</file>
</chapter>

<chapter>
<title>*filer-dual-window*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ミニバッファなどでディレクトリを入力した時に立ち上がるファイラを選択し
ます。 nil なら一画面ファイラ、non-nil なら二画面ファイラが起動します。
デフォルトは nil です。
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-eat-esc*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
nilなら、モードレスファイラでESCを押しても閉じません。
デフォルトは t です。
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-echo-filename*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
（途中）
ファイラのステータスウィンドウへのファイル名の表示を制御します。
ファイル名の表示は暇なときに行なっているようです。
  non-nil  暇なときに表示する
  nil      表示しない
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-format-comma*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
non-nilなら、ファイルサイズをカンマ区切りで表示します。
[共通設定] - [ファイラ] - [ファイルサイズをカンマ区切りで表示(C)] で値を
指定することができます。
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-guide-text*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラ下部に表示されるガイドテキストを設定します。

使用例：
  (setq *filer-guide-text*
      '("(A)ttribute  (B)yteCompile  (C)opy  (D)elete  (E)xtract  (F)ind"
        "(G)o  (J)ump  m(K)dir  &lt;L&gt;Cd  (M)ove  re(N)ame"))
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-last-command-char*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラにてコマンドを実行した時に最後に入力された文字を示します。
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-last-file-mask*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
一画面ファイラの初期のファイルマスクをリストで設定します。
</description>
<seealso>*filer-primary-file-mask*</seealso>
<seealso>*filer-secondary-file-mask*</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-left-window-p*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
二画面ファイラを閉じたとき、どちらのウィンドウがアクティブだったかが保存
されます。ファイラ未起動時の値は t です。

  nil     : 右側のウィンドウ
  non-nil : 左側のウィンドウ
<!--
  使用例：
  ; [xyzzy:07026]
  ; ファイラの起動時に表示するディレクトリを前回の終了時と同じに
  (register-history-variable '*filer-primary-directory*)
  (register-history-variable '*filer-secondary-directory*)
  (register-history-variable '*filer-left-window-p*) 
-->
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-mark-file-size-unit*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラのマークファイルの合計サイズの単位を指定します。
#\B, #\K, #\M, #\G, #\Tの何れかを指定可能です。ただし、例えば#\K
が設定されたとき、サイズが1K未満ならバイト単位になります。デフォ
ルトではnilに設定されています。

使用例：
  (setq *filer-mark-file-size-unit* #\M)
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-modal*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラの動作を指定します。

モーダルの場合には、ファイラはエディタとは同期的に動作します。
ファイラ起動中はエディタでの編集は不能です。
モードレスの場合には、ファイラはエディタとは非同期に動作します。
ファイラ起動中にエディタでの編集が可能です。

  t   モーダルで動作させます
  nil モードレスで動作させます
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file>filer.l</file>
</chapter>

<chapter>
<title>*filer-path-masks*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラのファイルマスクを設定します。

使用例：
  (pushnew '("Microsoft" "*.doc" "*.xls" "*.ppt" "*.sys" "*.bat" "*.ini")
           *filer-path-masks* :test 'equal)
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file>filer.l</file>
</chapter>

<chapter>
<title>*filer-primary-directory*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
二画面ファイラのアクティブな方のディレクトリを示します。
右側か左側かは *filer-left-window-p* の値によって決まります。
ファイラ未起動時は左側のディレクトリを指定できます。

使用例：
  ; [xyzzy:07218]
  ; 常にカレントディレクトリからファイラを起動する。
  (defun foo ()
    (interactive)
    (let ((*filer-primary-directory* nil)
          (*filer-secondary-directory* nil))
      (open-filer)))
</description>
<seealso>*filer-secondary-directory*</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-primary-file-mask*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラ左側の初期のファイルマスクをリストで設定します。

使用例：
  (setq *filer-primary-file-mask* '("*"))
</description>
<seealso>filer</seealso>
<seealso>*filer-secondary-file-mask*</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-retrieve-icon*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
non-nil のとき、ファイラでファイルタイプに応じたアイコンを表示します。
[共通設定] - [ファイラ] - [アイコンをファイルから取ってくる(I)] で値を指
定することができます。
</description>
<seealso></seealso>
<link></link>
<section>ファイラ</section>
<file>filer.l</file>
</chapter>

<chapter>
<title>*filer-secondary-directory*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
二画面ファイラのアクティブでない方のディレクトリを示します。
右側か左側かは *filer-left-window-p* の値によって決まります。
ファイラ未起動時は右側のディレクトリを指定できます。
</description>
<seealso>*filer-primary-directory*</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-secondary-file-mask*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラ右側の初期のファイルマスクをリストで設定します。

使用例：
  (setq *filer-secondary-file-mask* '("*"))
</description>
<seealso>*filer-primary-file-mask*</seealso>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file></file>
</chapter>

<chapter>
<title>*filer-use-recycle-bin*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
ファイラでファイルの削除にゴミ箱を使用するかを設定します。
  non-nil  ファイラで削除したときはゴミ箱行き
  nil      直接削除
</description>
<seealso>filer</seealso>
<link></link>
<section>ファイラ</section>
<file>filer.l</file>
</chapter>

<chapter>
<title>*find-file-file-not-found-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
find-file で指定されたファイルが存在しないときに実行されます。
※run-hook-with-args-until-successで実行されるので注意すること
</description>
<seealso>find-file</seealso>
<seealso>run-hook-with-args-until-success</seealso>
<link></link>
<section>変数と定数</section>
<file>files.l</file>
</chapter>

<chapter>
<title>*find-file-hooks*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
find-file および find-file-read-only で新しいファイルを開くたびに、最後に実行されます。
すでにファイルを開いているバッファが存在した場合には実行されません。
</description>
<seealso>*find-file-read-only-hook*</seealso>
<seealso>find-file-read-only</seealso>
<seealso>find-file</seealso>
<link></link>
<section>ファイルシステム</section>
<file>files.l</file>
</chapter>

<chapter>
<title>*find-file-read-only-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
find-file-read-only でファイルごとに最後に実行されます。
*find-file-hooks* と異なり、すでにファイルが開かれていた場合にも実行されます。
</description>
<seealso>*find-file-hooks*</seealso>
<seealso>find-file-read-only</seealso>
<link></link>
<section>ファイルシステム</section>
<file>files.l</file>
</chapter>

<chapter>
<title>*grep-directory-name-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
grep-dialogでgrep対象のディレクトリを個々に設定したい場合に実行
されます。
※funcallされるので注意すること
</description>
<seealso>*grep-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file>grepd.l</file>
</chapter>

<chapter>
<title>*grep-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
grep起動後に実行されます。
</description>
<seealso>*grepd-hook*</seealso>
<seealso>*before-grep-hook*</seealso>
<seealso>*before-grepd-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file>grep.l</file>
</chapter>

<chapter>
<title>*before-grep-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>
grep起動前に実行されます。
フックの引数は検索キーワード(or regex string)です。
フック実行時のselected-bufferはgrepバッファです。
</description>
<seealso>*grep-hook*</seealso>
<seealso>*grepd-hook*</seealso>
<seealso>*before-grepd-hook*</seealso>
<link></link>
<section>変数と定数</section>
<file>grep.l</file>
</chapter>

<chapter>
<title>*grepd-hook*</title>
<type>Variable</type>
<arguments></arguments>
<package>editor</package>
<description>